version: '3'
services:
  serv:
    build: ./server
    env_file:
      - .env
    working_dir: /app
    ports:
      - "5000:5000"
    restart: "unless-stopped"
    develop:
      watch:
        - action: rebuild
          path: ./server/index.js
          target: /app/index.js
        - action: rebuild
          path: ./server/package.json
          target: /app/package.json
    command: bash -c "npm install && node index.js"
  cli:
    build: ./client
    ports:
      - "3000:3000"
    restart: "unless-stopped"
    environment:
      - REACT_APP_LOCAL_IP_ADDR=${REACT_APP_LOCAL_IP_ADDR}
    develop:
      watch:
        - action: sync
          path: ./client/src
          target: /app/src
          ignore: 
            - node_modules
        - action: sync
          path: ./client/tailwind.config.js
          target: /app/tailwind.config.js
        - action: rebuild
          path: ./client/package.json
    command: bash -c "npm --verbose install  && npm start"
